// 🌕 /{lang}/chuseok/ 문안. 코드는 chuseok.js.
// 원칙: 숫자가 말하게 한다. 형용사로 부풀리지 않는다. 모르는 것은 모른다고 쓴다.
'use strict';
const SITE = '축제모아';

module.exports = {
  en: {
    title: (y, span) => `Chuseok ${y} in Korea (${span}) — What Actually Closes | ${SITE}`,
    desc: (y, span, r, c) => `Chuseok ${y} is ${span}. What closes, what stays open, and the Monday-after trap — read from opening-hours data for ${r} restaurants and ${c} cafés.`,
    h1: (y, span) => `Chuseok ${y}: ${span}`,
    lead: `Chuseok is Korea's biggest holiday. Most of the country travels to their hometown on the same days. If a friend is coming to Korea around then, this is the page to send them — it answers the question everyone living here gets asked every year: <b>"will anything be open?"</b>`,
    warnH: 'The short version',
    warnP: (offSpan, sun, mon) => `Official holidays are <b>${offSpan}</b>. ${sun} is a Sunday, so it is effectively a four-day break — and then <b>${mon} is a Monday</b>, the most common weekly closing day in Korea. Plan around both, not just the holiday.`,

    h2close: 'What actually closes',
    pClose: (r, c) => `We track opening hours for <b>${r} restaurants</b> and <b>${c} cafés</b> registered in Korea Tourism Organization data. Here is what they say themselves:`,
    thPlace: 'What the listing says', thR: 'Restaurants', thC: 'Cafés',
    rowHol: 'Says it closes for Chuseok / Lunar New Year',
    rowAlways: 'Says it is open year-round (연중무휴)',
    rowMon: 'Closes every Monday',
    closeWarn: (n, rest) => `<b>Read this carefully.</b> ${n} places saying "closed for the holiday" does <b>not</b> mean the other ${rest} are open. Most simply did not say. Many Korean businesses decide holiday hours about a week ahead and put a paper note on the door. If one specific place matters to you, call it.`,

    h2mon: 'The Monday-after trap',
    pMon: (mon, r, rp, c, cp) => `<b>${mon} is a Monday.</b> Monday is the single most common closing day in Korea — <b>${r} restaurants (${rp}%)</b> and <b>${c} cafés (${cp}%)</b> in our data close every Monday. So "we'll just go after the holiday" walks straight into it. The first fully normal day is the Tuesday.`,
    monLink: 'Full breakdown by weekday →',
    h2diff: 'How it differs from the holiday you may know',
    pDiff: `Chuseok falls on the 15th day of the 8th lunar month, so the date moves every year. Korea makes it a <b>three-day</b> public holiday — the day before, the day itself, and the day after. If you know American Thanksgiving, the feel is similar: family, food, and the entire country travelling at once. The difference is that Korea is small and the travel is compressed into those few days, which is why intercity buses, trains and highways fill up and why so many small businesses simply shut.`,

    h2open: 'What is open',
    pOpen: n => n ? `<b>${n} festivals</b> are running across the holiday. Festivals are one of the few things that stay open on Chuseok — many are timed for it.` : `We could not find a festival running across this holiday in our data. That is unusual; check the festival search below.`,
    festNone: 'No festival in our data runs across these dates.',

    h2mkt: 'Traditional markets, day by day',
    pMkt: n => `Korea's <b>five-day markets (오일장)</b> open on a fixed cycle of date endings, so we can say which ones fall on each holiday day. Of the <b>${n} markets</b> whose cycle we know:`,
    mktWarn: `<b>That is the rule, not a promise.</b> Many markets close on the holiday itself, and some run a larger market in the days <i>before</i> Chuseok instead. Treat these as candidates and confirm locally before travelling.`,
    mktUnit: n => `${n} markets`,
    mktLink: 'All five-day markets →',

    h2no: "What this page does not cover",
    pNo: `We only write what our own data supports. Visas and K-ETA, transport cards, SIM cards and flight prices are <b>not</b> our data, so we do not cover them. Plenty of sites do — and getting those wrong would cost you more than our staying quiet.`,
    src: (r, c, d) => `Source: Korea Tourism Organization public data (opening hours, festivals, traditional markets) and the Korean government public-holiday calendar. Opening-hours figures are counted from ${r} restaurants and ${c} cafés on ${d}. Businesses change holiday hours at short notice — always confirm before travelling.`,
    navClosed: '🚪 What closes, all year', navCal: '🗓️ When to go', navAcc: '♿ Barrier-free', navSearch: '🔎 Festivals'
  }
};

module.exports.ja = {
  title: (y, span) => `${y}年 秋夕チュソク（${span}）— 実際に何が閉まるのか | ${SITE}`,
  desc: (y, span, r, c) => `${y}年の秋夕は${span}。何が閉まり何が開いているか、そして連休明け月曜の落とし穴を、飲食店${r}軒・カフェ${c}軒の営業時間データから数えました。`,
  h1: (y, span) => `${y}年 秋夕チュソク：${span}`,
  lead: `秋夕（チュソク）は韓国最大の祝日です。国じゅうが同じ日に帰省します。その時期に韓国へ来る友人がいるなら、このページを送ってください。韓国に住む人が毎年必ず聞かれる質問 — <b>「どこか開いてる？」</b> に数字で答えます。`,
  warnH: 'まず結論から',
  warnP: (offSpan, sun, mon) => `法定祝日は<b>${offSpan}</b>。${sun}は日曜なので実質4連休で、さらに<b>${mon}は月曜</b> — 韓国で最も定休日が多い曜日です。連休だけでなく、その翌日まで含めて計画してください。`,
  h2close: '実際に閉まるもの',
  pClose: (r, c) => `韓国観光公社の公開データに登録された<b>飲食店${r}軒</b>・<b>カフェ${c}軒</b>の営業時間を集計しています。店側の記載はこうなっています。`,
  thPlace: '記載内容', thR: '飲食店', thC: 'カフェ',
  rowHol: '「旧正月・秋夕は休み」と明記',
  rowAlways: '「年中無休」と明記',
  rowMon: '毎週月曜が定休',
  closeWarn: (n, rest) => `<b>ここを誤解しないでください。</b>「祝日休み」と書いた店が${n}軒あるからといって、残りの${rest}軒が開いているという意味では<b>ありません</b>。多くは<b>書いていないだけ</b>です。韓国では祝日の営業を1週間ほど前に決め、紙の貼り紙で告知する店が少なくありません。どうしても行きたい店があるなら電話で確認を。`,
  h2mon: '連休明け月曜の落とし穴',
  pMon: (mon, r, rp, c, cp) => `<b>${mon}は月曜です。</b>月曜は韓国で最も定休日が集中する曜日で、当データでも<b>飲食店${r}軒（${rp}%）</b>・<b>カフェ${c}軒（${cp}%）</b>が毎週月曜休みです。「連休が明けてから行こう」がそのまま罠になります。通常営業に戻るのは火曜からです。`,
  monLink: '曜日別の内訳を見る →',
  h2diff: '日本のお盆との違い',
  pDiff: `秋夕は旧暦8月15日なので、毎年日付が動きます。韓国では<b>前日・当日・翌日の3日間</b>が法定祝日です。帰省が集中するという点はお盆と似ていますが、<b>お盆は法定祝日ではない</b>のに対し秋夕は3日まとめて休みになるため、帰省の集中度と休業の規模がまるで違います。高速道路・高速バス・KTXはこの数日に一気に混みます。`,
  h2open: '開いているもの',
  pOpen: n => n ? `連休をまたいで<b>${n}件の祭り</b>が開催中です。祭りは秋夕に開いている数少ないものの一つで、むしろこの時期に合わせて行われるものもあります。` : `この連休をまたぐ祭りはデータ内に見つかりませんでした。下の祭り検索で確認してください。`,
  festNone: 'この期間に開催される祭りはデータにありません。',
  h2mkt: '五日市（オイルジャン）を日ごとに',
  pMkt: n => `韓国の<b>五日市（오일장）</b>は日付の下一桁で開催日が決まるため、連休のどの日にどの市が立つかを機械的に出せます。開催サイクルが分かっている<b>${n}か所</b>のうち:`,
  mktWarn: `<b>これは規則であって保証ではありません。</b>祝日当日は休む市が多く、逆に秋夕<i>前</i>に大きな市を立てるところもあります。候補として見て、行く前に現地で確認してください。`,
  mktUnit: n => `${n}か所`,
  mktLink: '五日市の一覧 →',
  h2no: 'このページが扱わないもの',
  pNo: `自分たちのデータで裏づけられることだけを書いています。ビザ・K-ETA、交通カード、SIM、航空券の価格は<b>私たちのデータではない</b>ので扱いません。それを扱うサイトは他にたくさんあり、私たちが誤った情報を書くほうがあなたにとって害になります。`,
  src: (r, c, d) => `出典：韓国観光公社の公開データ（営業時間・祭り・伝統市場）と韓国政府の祝日カレンダー。営業時間の集計は${d}時点の飲食店${r}軒・カフェ${c}軒に基づきます。祝日の営業は直前に変わることがあるため、必ず事前確認を。`,
  navClosed: '🚪 休む日（通年）', navCal: '🗓️ いつ行くか', navAcc: '♿ バリアフリー', navSearch: '🔎 お祭り検索'
};

module.exports.es = {
  title: (y, span) => `Chuseok ${y} en Corea (${span}) — Qué cierra de verdad | ${SITE}`,
  desc: (y, span, r, c) => `El Chuseok ${y} cae ${span}. Qué cierra, qué sigue abierto y la trampa del lunes siguiente, contado desde los horarios de ${r} restaurantes y ${c} cafeterías.`,
  h1: (y, span) => `Chuseok ${y}: ${span}`,
  lead: `El Chuseok es la mayor festividad de Corea. Casi todo el país viaja a su ciudad natal los mismos días. Si un amigo tuyo viene a Corea por esas fechas, esta es la página que conviene enviarle: responde con números a la pregunta que todo residente escucha cada año — <b>«¿habrá algo abierto?»</b>`,
  warnH: 'En resumen',
  warnP: (offSpan, sun, mon) => `Los festivos oficiales son <b>${offSpan}</b>. El ${sun} es domingo, así que en la práctica son cuatro días — y además <b>el ${mon} es lunes</b>, el día de cierre semanal más común en Corea. Planifica contando también con ese lunes.`,
  h2close: 'Qué cierra realmente',
  pClose: (r, c) => `Seguimos los horarios de <b>${r} restaurantes</b> y <b>${c} cafeterías</b> registrados en los datos públicos de la Organización de Turismo de Corea. Esto es lo que declaran ellos mismos:`,
  thPlace: 'Lo que declara el local', thR: 'Restaurantes', thC: 'Cafeterías',
  rowHol: 'Declara que cierra en Chuseok / Año Nuevo Lunar',
  rowAlways: 'Declara abrir todo el año (연중무휴)',
  rowMon: 'Cierra todos los lunes',
  closeWarn: (n, rest) => `<b>Léelo con cuidado.</b> Que ${n} locales digan «cerrado por festivo» <b>no</b> significa que los otros ${rest} abran. La mayoría simplemente no lo indicó. Muchos negocios coreanos deciden el horario festivo con una semana de antelación y lo anuncian con un papel en la puerta. Si un sitio concreto te importa, llama.`,
  h2mon: 'La trampa del lunes siguiente',
  pMon: (mon, r, rp, c, cp) => `<b>El ${mon} es lunes.</b> El lunes es con diferencia el día de cierre más habitual en Corea: <b>${r} restaurantes (${rp}%)</b> y <b>${c} cafeterías (${cp}%)</b> de nuestros datos cierran todos los lunes. Así que «vamos justo después del festivo» cae de lleno en la trampa. El primer día plenamente normal es el martes.`,
  monLink: 'Desglose por día de la semana →',
  h2diff: 'En qué se diferencia de la fiesta que ya conoces',
  pDiff: `El Chuseok cae el día 15 del octavo mes lunar, así que la fecha cambia cada año. Corea lo convierte en un festivo de <b>tres días</b>: la víspera, el día en sí y el día siguiente. Si conoces el Día de Acción de Gracias estadounidense, la sensación es parecida: familia, comida y todo el país viajando a la vez. La diferencia es que Corea es pequeña y ese desplazamiento se concentra en pocos días, por eso se llenan autobuses interurbanos, trenes y autopistas, y por eso cierran tantos negocios pequeños.`,
  h2open: 'Qué sí está abierto',
  pOpen: n => n ? `Hay <b>${n} festivales</b> en marcha durante el puente. Los festivales son de lo poco que sigue abierto en Chuseok; algunos se programan precisamente para estas fechas.` : `No encontramos festivales activos en estas fechas dentro de nuestros datos. Consulta el buscador de festivales.`,
  festNone: 'Ningún festival de nuestros datos coincide con estas fechas.',
  h2mkt: 'Mercados tradicionales, día a día',
  pMkt: n => `Los <b>mercados de cinco días (오일장)</b> abren según la última cifra de la fecha, así que podemos decir cuáles caen en cada día del puente. De los <b>${n} mercados</b> cuyo ciclo conocemos:`,
  mktWarn: `<b>Es la regla, no una garantía.</b> Muchos mercados cierran el día festivo, y otros montan un mercado mayor en los días <i>previos</i> al Chuseok. Tómalos como candidatos y confirma en destino antes de viajar.`,
  mktUnit: n => `${n} mercados`,
  mktLink: 'Todos los mercados de cinco días →',
  h2no: 'Lo que esta página no cubre',
  pNo: `Solo escribimos lo que nuestros datos respaldan. Los visados y el K-ETA, las tarjetas de transporte, las SIM y los precios de vuelos <b>no</b> son datos nuestros, así que no los tratamos. Hay muchas webs que sí lo hacen, y equivocarnos ahí te costaría más que nuestro silencio.`,
  src: (r, c, d) => `Fuente: datos públicos de la Organización de Turismo de Corea (horarios, festivales, mercados tradicionales) y el calendario oficial de festivos del Gobierno de Corea. Los recuentos de horarios provienen de ${r} restaurantes y ${c} cafeterías el ${d}. Los negocios cambian el horario festivo con poca antelación: confirma siempre antes de viajar.`,
  navClosed: '🚪 Qué cierra (todo el año)', navCal: '🗓️ Cuándo ir', navAcc: '♿ Accesibilidad', navSearch: '🔎 Buscar festivales'
};

module.exports.zh = {
  title: (y, span) => `${y}年韩国秋夕（${span}）— 到底什么会关门 | ${SITE}`,
  desc: (y, span, r, c) => `${y}年秋夕为${span}。哪些关门、哪些照常营业，以及假期后周一的陷阱 —— 依据${r}家餐厅和${c}家咖啡馆的营业时间数据统计。`,
  h1: (y, span) => `${y}年秋夕：${span}`,
  lead: `秋夕是韩国最大的节日，全国在同几天集中返乡。如果有朋友那时来韩国，把这一页发给他就够了 —— 它用数字回答每个住在韩国的人每年都会被问到的问题：<b>「有地方开门吗？」</b>`,
  warnH: '先说结论',
  warnP: (offSpan, sun, mon) => `法定假日是<b>${offSpan}</b>。${sun}是周日，所以实际上是四天连休；而且<b>${mon}是周一</b> —— 韩国每周固定歇业最集中的一天。安排行程时要把这个周一也算进去。`,
  h2close: '到底什么会关门',
  pClose: (r, c) => `我们统计了韩国观光公社公开数据中<b>${r}家餐厅</b>和<b>${c}家咖啡馆</b>的营业时间。店家自己是这样写的：`,
  thPlace: '店家标注', thR: '餐厅', thC: '咖啡馆',
  rowHol: '写明「春节·秋夕休息」',
  rowAlways: '写明「全年无休」',
  rowMon: '每周一固定休息',
  closeWarn: (n, rest) => `<b>这里请不要误读。</b>有${n}家写了「节日休息」，<b>并不代表</b>其余${rest}家会开门。大多数只是<b>没有写</b>。韩国不少店铺在节前一周才决定假期营业时间，然后在门口贴一张纸告知。如果有非去不可的店，请直接打电话确认。`,
  h2mon: '假期后周一的陷阱',
  pMon: (mon, r, rp, c, cp) => `<b>${mon}是周一。</b>周一是韩国歇业最集中的一天 —— 我们的数据中有<b>${r}家餐厅（${rp}%）</b>和<b>${c}家咖啡馆（${cp}%）</b>每周一休息。所以「等假期过了再去」正好撞上。真正恢复正常的是周二。`,
  monLink: '查看各星期几的分布 →',
  h2diff: '和你熟悉的中秋节有什么不同',
  pDiff: `韩国秋夕和中秋节是同一天 —— 农历八月十五，所以公历日期每年都不一样。不同的是，韩国把它定为<b>三天</b>法定假日：前一天、当天、后一天。中国的中秋通常只放一天，因此韩国的返乡潮和停业规模要大得多。高速公路、长途巴士和KTX会在这几天集中拥堵，很多个体小店干脆整个连假都不开门。`,
  h2open: '什么是开着的',
  pOpen: n => n ? `连休期间有<b>${n}个庆典</b>正在举行。庆典是秋夕期间少数照常开放的活动之一，有些甚至就是为这个时期安排的。` : `我们的数据中没有横跨这几天的庆典。请用下面的庆典搜索查询。`,
  festNone: '数据中没有横跨这几天的庆典。',
  h2mkt: '传统五日市集，逐日看',
  pMkt: n => `韩国的<b>五日市集（오일장）</b>按日期尾数固定开市，因此可以推算连休每一天有哪些市集。在已知开市周期的<b>${n}处</b>中：`,
  mktWarn: `<b>这是规则，不是保证。</b>不少市集在节日当天休市，也有些会在秋夕<i>前几天</i>开更大的市。请把它们当作候选，出发前再确认。`,
  mktUnit: n => `${n}处`,
  mktLink: '全部五日市集 →',
  h2no: '本页不涉及的内容',
  pNo: `我们只写自己的数据能支撑的内容。签证与K-ETA、交通卡、手机SIM卡、机票价格<b>不是</b>我们的数据，所以不写。这些内容有很多网站在做，我们写错反而会害了你。`,
  src: (r, c, d) => `资料来源：韩国观光公社公开数据（营业时间·庆典·传统市场）与韩国政府法定假日日历。营业时间统计基于${d}的${r}家餐厅和${c}家咖啡馆。店家常在临近时改动假期营业时间，出行前请务必确认。`,
  navClosed: '🚪 哪天关门（全年）', navCal: '🗓️ 什么时候去', navAcc: '♿ 无障碍', navSearch: '🔎 庆典搜索'
};

module.exports.tw = {
  title: (y, span) => `${y}年韓國秋夕（${span}）— 到底什麼會關門 | ${SITE}`,
  desc: (y, span, r, c) => `${y}年秋夕為${span}。哪些關門、哪些照常營業，以及連假後週一的陷阱 —— 依據${r}家餐廳與${c}家咖啡廳的營業時間資料統計。`,
  h1: (y, span) => `${y}年秋夕：${span}`,
  lead: `秋夕是韓國最大的節日，全國在同幾天集中返鄉。如果有朋友那時要來韓國，把這一頁傳給他就夠了 —— 它用數字回答每個住在韓國的人每年都會被問到的問題：<b>「有地方開門嗎？」</b>`,
  warnH: '先說結論',
  warnP: (offSpan, sun, mon) => `法定假日是<b>${offSpan}</b>。${sun}是週日，所以實際上是四天連假；而且<b>${mon}是週一</b> —— 韓國每週固定公休最集中的一天。安排行程時要把這個週一也算進去。`,
  h2close: '到底什麼會關門',
  pClose: (r, c) => `我們統計了韓國觀光公社公開資料中<b>${r}家餐廳</b>與<b>${c}家咖啡廳</b>的營業時間。店家自己是這樣寫的：`,
  thPlace: '店家標註', thR: '餐廳', thC: '咖啡廳',
  rowHol: '寫明「春節·秋夕休息」',
  rowAlways: '寫明「全年無休」',
  rowMon: '每週一固定公休',
  closeWarn: (n, rest) => `<b>這裡請不要誤讀。</b>有${n}家寫了「節日休息」，<b>並不代表</b>其餘${rest}家會開門。大多數只是<b>沒有寫</b>。韓國不少店家在節前一週才決定連假營業時間，然後在門口貼一張紙公告。如果有非去不可的店，請直接打電話確認。`,
  h2mon: '連假後週一的陷阱',
  pMon: (mon, r, rp, c, cp) => `<b>${mon}是週一。</b>週一是韓國公休最集中的一天 —— 我們的資料中有<b>${r}家餐廳（${rp}%）</b>與<b>${c}家咖啡廳（${cp}%）</b>每週一公休。所以「等連假過了再去」正好撞上。真正恢復正常的是週二。`,
  monLink: '查看各星期幾的分布 →',
  h2diff: '和你熟悉的中秋節有什麼不同',
  pDiff: `韓國秋夕和中秋節是同一天 —— 農曆八月十五，所以國曆日期每年都不一樣。不同的是，韓國把它定為<b>三天</b>法定假日：前一天、當天、後一天。台灣的中秋通常只放一天，因此韓國的返鄉潮和停業規模要大得多。高速公路、國道客運和KTX會在這幾天集中壅塞，很多個體小店乾脆整個連假都不開門。`,
  h2open: '什麼是開著的',
  pOpen: n => n ? `連假期間有<b>${n}個慶典</b>正在舉行。慶典是秋夕期間少數照常開放的活動之一，有些甚至就是為這個時期安排的。` : `我們的資料中沒有橫跨這幾天的慶典。請用下面的慶典搜尋查詢。`,
  festNone: '資料中沒有橫跨這幾天的慶典。',
  h2mkt: '傳統五日市集，逐日看',
  pMkt: n => `韓國的<b>五日市集（오일장）</b>依日期尾數固定開市，因此可以推算連假每一天有哪些市集。在已知開市週期的<b>${n}處</b>中：`,
  mktWarn: `<b>這是規則，不是保證。</b>不少市集在節日當天休市，也有些會在秋夕<i>前幾天</i>開更大的市。請把它們當作候選，出發前再確認。`,
  mktUnit: n => `${n}處`,
  mktLink: '全部五日市集 →',
  h2no: '本頁不涉及的內容',
  pNo: `我們只寫自己的資料能支撐的內容。簽證與K-ETA、交通卡、手機SIM卡、機票價格<b>不是</b>我們的資料，所以不寫。這些內容有很多網站在做，我們寫錯反而會害了你。`,
  src: (r, c, d) => `資料來源：韓國觀光公社公開資料（營業時間·慶典·傳統市場）與韓國政府法定假日行事曆。營業時間統計基於${d}的${r}家餐廳與${c}家咖啡廳。店家常在臨近時變動連假營業時間，出發前請務必確認。`,
  navClosed: '🚪 哪天關門（全年）', navCal: '🗓️ 什麼時候去', navAcc: '♿ 無障礙', navSearch: '🔎 慶典搜尋'
};
