// 🌐 intl.js 가 쓰는 5개 언어 문안.
// ⚠️ 원칙: **숫자는 전부 인자로 받는다.** 문장 안에 숫자를 박아두면 데이터가 바뀌었을 때 조용히 거짓말이 된다.
// ⚠️ 원칙: 우리 데이터로 확인한 것만 쓴다. K-ETA·환율·유심·날씨는 우리 데이터가 아니라 여기 없다.
'use strict';

const en = {
  nav: { cal: '🗓️ When to go', acc: '♿ Barrier-free', trend: '🔥 Rankings', search: '🔎 Festivals', closed: '🚪 What closes when', trip: '🧳 1st/2nd/3rd visit' },
  daysUnit: (n) => (n === 1 ? ' day' : ' days'),
  cl: {
    title: 'What closes when in Korea — public holidays, weekly closing days, break times | Chukjemoa',
    desc: 'Which days shops and restaurants in Korea are shut. Built from the opening hours of thousands of Korea Tourism Organization–listed restaurants and cafés, plus the official public holiday calendar.',
    h1: 'What is closed when — the days your plan quietly falls apart',
    lead: (tot, worstN, worstDay) => `Korea has two closing patterns that catch visitors out: national holidays, when a large share of small businesses shut for several days at once, and a fixed weekly rest day. We counted the published opening hours of <b>${tot}</b> restaurants and cafés listed by the Korea Tourism Organization. <b>${worstN}</b> of them close every <b>${worstDay}</b>. This page is only about opening days — not about visas, money or transport, which we have no data on.`,
    warnH: (name) => `The next long closure: ${name}`,
    warnP: (from, to, n) => `<b>${from} – ${to}.</b> This is the biggest domestic travel period of the year. Trains and intercity buses sell out weeks ahead, and family-run businesses close — <b>${n}</b> of the restaurants and cafés in our data explicitly list national holidays as a closing day, and many more close without announcing it. Palaces and large museums usually stay open; small local restaurants usually do not. If your dates fall inside this window, plan around department stores, chain cafés and convenience stores, which stay open.`,
    h2hol: 'Public holidays ahead',
    pHol: (n) => `${n} public holiday dates are scheduled from today onward. Consecutive dates are grouped, because a three-day holiday behaves very differently from a single day off.`,
    thDate: 'Date', thName: 'Holiday', thDays: 'Length',
    holNote: 'Substitute holidays are added when a holiday falls on a weekend. Government offices, banks and post offices close on all of these. Most tourist attractions stay open; small businesses vary.',
    h2week: 'The weekly closing day',
    pWeek: (n, day, dn, pct) => `Almost every Korean restaurant has one fixed day off each week, and it is not usually posted in English. Of the <b>${n}</b> restaurants in our data, <b>${dn}</b> — about <b>${pct}%</b> — close on <b>${day}</b>. That is the single most common closing day, by a wide margin.`,
    h3cafe: 'Cafés follow the same pattern',
    pCafe: (n, day, dn) => `Of <b>${n}</b> cafés, <b>${dn}</b> close on <b>${day}</b>.`,
    weekNote: 'Counted from the closing-day text each business registered with the Korea Tourism Organization. Businesses that did not register a closing day are not counted here, so the real numbers are higher, not lower.',
    h2break: 'The afternoon break — why you cannot get lunch at 3pm',
    pBreak: (n, pct, cafeN) => `<b>${n}</b> restaurants — about <b>${pct}%</b> of the ones we hold — publish a mid-afternoon break or a last-order time. Typically the kitchen shuts somewhere between 15:00 and 17:00 and reopens for dinner. <b>${cafeN}</b> cafés publish one too.`,
    pBreak2: 'This is the most common way a well-planned afternoon goes wrong: you finish a morning attraction at 14:30, walk twenty minutes to the restaurant you saved, and arrive during the break. Eat before 14:00 or after 17:00, or check the last-order time before you set off.',
    h2good: 'The good news',
    pGood: (n, pct, cafeN) => `<b>${n}</b> restaurants — <b>${pct}%</b> — register as open every day of the year, along with <b>${cafeN}</b> cafés. Convenience stores are genuinely 24-hour and are everywhere. You will not go hungry in Korea; you will just occasionally not eat the specific thing you planned.`,
    pGood2: 'Department stores, large chains and subway-adjacent food courts keep the most reliable hours. Small owner-run places keep the least reliable ones — and they are usually the ones worth going to.',
    h2how: 'How to check a specific place yourself',
    pHow: 'Opening hours in Korea are most accurate on Naver Map and Kakao Map, not on Google Maps. Both work better if you search the Korean name, which is why every place on this site is shown with its Korean name next to the romanised one. Copy the Korean text, paste it into the search box, and read the hours line.',
    src: (rn, cn, d) => `Source: Korea Tourism Organization TourAPI — opening hours and closing days for ${rn} restaurants and ${cn} cafés · public holiday dates from the Korean government open data portal. Counted on ${d}. Hours change without notice; confirm before you travel.`
  },
  ac: {
    title: 'Barrier-free travel in Korea — registered accessible places by region | Chukjemoa',
    desc: 'Places in Korea registered as barrier-free with the Korea Tourism Organization, broken down by type and region, with an honest account of what the data does and does not cover.',
    h1: 'Barrier-free travel in Korea — what is actually on record',
    lead: (n) => `<b>${n}</b> places in Korea are registered in the Korea Tourism Organization's barrier-free tourism database. That is the largest single list of its kind, and almost none of it has ever been published in English. This page shows what is in it, where those places are, and — just as importantly — where the data is thin, so you do not plan a trip on numbers that do not mean what they look like.`,
    h2cat: 'What kind of places',
    pCat: (attr, rest) => `Attractions make up the largest group at <b>${attr}</b>, followed by restaurants at <b>${rest}</b>. Registration means the operator submitted accessibility information to the national tourism database — it is a starting point for research, not a guarantee that a specific need is met.`,
    thCat: 'Type', thN: 'Places',
    h2region: 'Where they are',
    pRegion: (top, n, seoul, sn) => `<b>${top}</b> has the most registered places at <b>${n}</b>. ${seoul} has <b>${sn}</b>. Note that this reflects how thoroughly each province surveyed its venues as much as how accessible they are — a low number means less was recorded, not necessarily that less is accessible.`,
    h2limit: 'Read this before you trust the detail tags',
    pLimit: (wheel, topN, topSido) => `The database also carries detailed tags such as "wheelchair access". <b>${wheel}</b> places carry the wheelchair tag — but <b>${topN}</b> of those are in <b>${topSido}</b> alone. This is a survey artefact: one province recorded detailed tags and the others largely did not. <b>So the absence of a wheelchair tag tells you almost nothing outside that province.</b> We are showing you this rather than hiding it, because a map built on these tags would be actively misleading.`,
    h2tags: 'The detail tags that exist',
    pTags: 'Counts across the whole database. Read them as "this many records were tagged", not as "this many places in Korea have this".',
    thTag: 'Feature',
    tag: { '휠체어': 'Wheelchair access', '장애인주차': 'Accessible parking', '장애인화장실': 'Accessible toilet', '엘리베이터': 'Elevator', '유아·수유': 'Baby care / nursing room', '시각약자': 'Support for visual impairment', '청각약자': 'Support for hearing impairment' },
    h2how: 'How to use this',
    pHow: 'Treat the registry as a shortlist, then verify each place directly — by phone, or by asking the venue in Korean. Step-free entry, toilet dimensions and lift availability are exactly the details that change after a renovation and are rarely updated in a national database. Subway stations in Seoul are far better documented than restaurants anywhere; the further from a metropolitan area you go, the more you should call ahead.',
    src: (n, d) => `Source: Korea Tourism Organization TourAPI — barrier-free tourism information, ${n} records. Counted on ${d}. We do not hold step heights, door widths, toilet dimensions or lift status, and we do not claim any place is suitable for a specific need.`
  },
  cal: {
    title: 'When to visit Korea — festivals by month, holidays and crowding | Chukjemoa',
    desc: 'How many festivals run in each upcoming month in Korea, which public holidays fall where, and which regions get busiest — from Korea Tourism Organization data.',
    h1: 'When to visit Korea — what is actually on, month by month',
    lead: (n, months) => `<b>${n}</b> festivals are currently running or scheduled across Korea, spread over <b>${months}</b> months. Most travel guides tell you Korea is nice in spring and autumn. This page tells you something more useful: exactly how many events run in each month, which holidays will close things while you are there, and which parts of the country fill up.`,
    h2now: 'Happening right now',
    pNow: (n) => `<b>${n}</b> festivals are open today. These are the ones you could reach this week.`,
    until: 'until',
    h2reg: 'Where the festivals actually are',
    pReg: (top, n, regions, share) => `Upcoming festivals are spread across <b>${regions}</b> provinces and metropolitan cities. <b>${top}</b> has the most, with <b>${n}</b> — and even that is only <b>${share}%</b> of the total. Korean festivals are not concentrated in one place; most of them happen where a first-time itinerary never goes.`,
    regNote: 'Counted from festivals currently running or scheduled. A province made up of many small counties will naturally show more events than a single city.',
    h2months: 'Month by month',
    pMonths: (min) => `Festival counts are from the national tourism database. Months with at least ${min} events have their own page listing every one of them.`,
    thMonth: 'Month', thFes: 'Festivals', thHol: 'Public holidays',
    h2season: 'What each season is actually for',
    pSeason: 'Derived from how visitor numbers move across the country, not from opinion — these are the months when the relevant places measurably fill up.',
    thWhat: 'What', thBest: 'Peak month',
    thVal: 'Valleys and swimming', thMap: 'Autumn foliage', thFlo: 'Spring blossoms', thOns: 'Hot springs',
    seasonNote: (ms) => `Visitor movement is measured for months ${ms} only, so peak months are drawn from those measurements. Source: Korea Tourism Data Lab, visitor counts per district.`,
    h2names: 'Why every name here has Korean next to it',
    pNames: 'Korean festivals are listed in the national database under their Korean names, and roughly half have no official English title. Where an official translation exists we use it; otherwise we romanise. Either way the Korean original is shown, because that is the string that works when you paste it into Naver Map or Kakao Map — which are the map apps that actually work in Korea.',
    noTrans: 'no official translation',
    mapLink: 'Open in Kakao Map →',
    mTitle: (m) => `Festivals in Korea — ${m}`,
    mLead: (n, m) => `<b>${n}</b> festivals are running or scheduled in ${m}. Every one of them is listed below with its dates, region and a map link.`,
    mHolH: 'Public holidays this month',
    mHolP: 'Expect small businesses to close and intercity transport to fill up around these dates. See <a href="../../closed/">what closes when</a> for the detail.',
    mFesH: (m) => `Everything on in ${m}`,
    mFesP: 'Sorted by start date. Names in grey are the Korean originals — paste them into Naver Map or Kakao Map to find the venue.',
    mBusyH: 'Which regions fill up',
    mBusyP: (m) => `Districts whose visitor numbers rise the most in ${m}, compared with their own yearly average. A figure of ×1.5 means half again as many people as usual.`,
    mBusyAlt: (m, meas) => `Visitor movement is not measured for ${m}, so this shows ${meas}, the nearest month we have measurements for. A figure of ×1.5 means half again as many people as usual in that district.`,
    mBusyNote: 'Source: Korea Tourism Data Lab, visitor counts per district. These are estimates based on mobile and card data, and they describe the whole district — not the specific venue.',
    mMeta: (m) => `Korean festivals in ${m} — full list with dates and locations | Chukjemoa`,
    mDesc: (n, m) => `All ${n} festivals running in Korea in ${m}, with dates, regions, Korean names and map links, plus the public holidays and crowding for that month.`
  }
};

const ja = {
  nav: { cal: '🗓️ いつ行くか', acc: '♿ バリアフリー', trend: '🔥 人気ランキング', search: '🔎 お祭り検索', closed: '🚪 休む日', trip: '🧳 何回目の訪韓' },
  daysUnit: () => '日間',
  cl: {
    title: '韓国で店が閉まる日 — 祝日・定休日・ブレイクタイム | Chukjemoa',
    desc: '韓国で飲食店やカフェが閉まる日を、韓国観光公社に登録された数千店の営業時間データと公式祝日カレンダーから数えました。',
    h1: '閉まっている日 — 予定が静かに崩れるところ',
    lead: (tot, worstN, worstDay) => `韓国で旅程が崩れる原因は二つあります。連休に個人店が一斉に閉まること、そして<b>週に一日の定休日</b>があることです。韓国観光公社に登録された飲食店・カフェ<b>${tot}</b>軒の営業時間を数えたところ、<b>${worstN}</b>軒が毎週<b>${worstDay}</b>に休んでいました。このページは「開いているかどうか」だけを扱います。ビザ・両替・交通は当サイトにデータがないので書きません。`,
    warnH: (name) => `次の大型連休：${name}`,
    warnP: (from, to, n) => `<b>${from} 〜 ${to}。</b>一年で最も人が動く時期です。KTXも高速バスも数週間前に売り切れ、家族経営の店は閉まります。当サイトのデータでも<b>${n}</b>軒が「名節休業」と明記しており、告知せずに閉める店はさらに多いです。宮殿や大型美術館はたいてい開いていますが、路地の食堂は閉まります。この期間に当たる場合は、デパート・チェーン店・コンビニを軸に組み立ててください。`,
    h2hol: 'これからの祝日',
    pHol: (n) => `本日以降に<b>${n}</b>日の祝日があります。三連休と単発の休日では影響がまったく違うので、連続する日はまとめて表示しています。`,
    thDate: '日付', thName: '祝日', thDays: '日数',
    holNote: '祝日が週末と重なると振替休日が付きます。官公庁・銀行・郵便局はすべて休みます。観光施設はおおむね開いていますが、個人店は店によります。',
    h2week: '週に一日の定休日',
    pWeek: (n, day, dn, pct) => `韓国の飲食店はほぼ必ず週一日の定休日を持ち、それは日本語でも英語でも掲示されていません。データ内の<b>${n}</b>軒のうち<b>${dn}</b>軒、およそ<b>${pct}%</b>が<b>${day}</b>に休みます。他の曜日と比べて突出しています。`,
    h3cafe: 'カフェも同じ傾向です',
    pCafe: (n, day, dn) => `カフェ<b>${n}</b>軒のうち<b>${dn}</b>軒が<b>${day}</b>に休みます。`,
    weekNote: '各店が韓国観光公社に登録した「休業日」欄の記述から数えました。休業日を登録していない店は数に入っていないので、実際の数はこれより多くなります。',
    h2break: 'ブレイクタイム — 15時に昼食が食べられない理由',
    pBreak: (n, pct, cafeN) => `<b>${n}</b>軒、当サイト保有分の約<b>${pct}%</b>が、午後の休憩時間かラストオーダーを明記しています。多くは15:00〜17:00の間に厨房を閉め、夕方に再開します。カフェも<b>${cafeN}</b>軒が明記しています。`,
    pBreak2: '午後の予定が崩れる典型がこれです。14:30に午前の観光を終え、20分歩いて目当ての店に着き、ブレイクタイムに当たる。14:00より前か17:00より後に食べるか、出発前にラストオーダーの時刻を確認してください。',
    h2good: '良い知らせ',
    pGood: (n, pct, cafeN) => `飲食店<b>${n}</b>軒（<b>${pct}%</b>）とカフェ<b>${cafeN}</b>軒が年中無休で登録されています。コンビニは本当に24時間で、どこにでもあります。韓国で食べ物に困ることはありません。困るのは「予定していたその一軒」に入れないときだけです。`,
    pGood2: 'デパート・大型チェーン・駅直結のフードコートが最も読みやすい営業時間です。逆に読みにくいのは個人店で、そして行く価値があるのはたいていそちらです。',
    h2how: '特定の店を自分で確認する方法',
    pHow: '韓国の営業時間は Google マップより NAVER 地図・カカオマップのほうが正確です。どちらも「ハングルの店名」で検索したほうが確実に出ます。当サイトが地名や店名にハングルを併記しているのはそのためです。ハングルをコピーして検索欄に貼り、営業時間の行を読んでください。',
    src: (rn, cn, d) => `出典：韓国観光公社 TourAPI — 飲食店${rn}軒・カフェ${cn}軒の営業時間と休業日／祝日は韓国政府の公共データ。集計日 ${d}。営業時間は予告なく変わります。出発前にご確認ください。`
  },
  ac: {
    title: '韓国のバリアフリー旅行 — 登録施設を地域別に | Chukjemoa',
    desc: '韓国観光公社のバリアフリー観光情報に登録された施設を、種類別・地域別に整理しました。データで分かることと分からないことも明記しています。',
    h1: '韓国のバリアフリー旅行 — 記録に残っているもの',
    lead: (n) => `韓国観光公社のバリアフリー観光情報には<b>${n}</b>件の施設が登録されています。この種の一覧としては国内最大ですが、日本語で公開されたことはほとんどありません。このページでは、そこに何が入っていて、どこにあり、そして<b>どこが薄いのか</b>までお見せします。数字の意味を取り違えたまま旅程を組まないためです。`,
    h2cat: '施設の種類',
    pCat: (attr, rest) => `最も多いのは観光地で<b>${attr}</b>件、次いで飲食店が<b>${rest}</b>件です。「登録あり」は事業者が国のデータベースにバリアフリー情報を提出したという意味で、特定の必要を満たす保証ではありません。調べ始める地点だと考えてください。`,
    thCat: '種類', thN: '件数',
    h2region: '地域の分布',
    pRegion: (top, n, seoul, sn) => `最も多いのは<b>${top}</b>で<b>${n}</b>件、${seoul}は<b>${sn}</b>件です。これはバリアフリーの度合いというより<b>各自治体がどれだけ丁寧に調査したか</b>を反映しています。数が少ない地域は「記録が少ない」のであって「使える施設が少ない」とは限りません。`,
    h2limit: '詳細タグを信じる前に読んでください',
    pLimit: (wheel, topN, topSido) => `このデータには「車椅子」などの詳細タグも付いています。車椅子タグが付いているのは<b>${wheel}</b>件ですが、そのうち<b>${topN}</b>件が<b>${topSido}</b>に集中しています。これは調査の偏りで、一つの道だけが詳細タグを記録し、他はほとんど記録していません。<b>つまり、その道の外では「タグが無い＝対応していない」とは全く言えません。</b>隠さずに書くのは、このタグで地図を作ると誤解を招くからです。`,
    h2tags: '存在する詳細タグ',
    pTags: 'データベース全体の件数です。「韓国にこれだけある」ではなく「これだけの記録にタグが付いている」と読んでください。',
    thTag: '項目',
    tag: { '휠체어': '車椅子対応', '장애인주차': '身障者用駐車場', '장애인화장실': '身障者用トイレ', '엘리베이터': 'エレベーター', '유아·수유': 'ベビーケア・授乳室', '시각약자': '視覚障害への配慮', '청각약자': '聴覚障害への配慮' },
    h2how: '使い方',
    pHow: 'この一覧は候補を絞るために使い、最後は必ず個別に確認してください。段差の有無・トイレの広さ・エレベーターの稼働は、改装のたびに変わり、国のデータベースにはまず反映されません。ソウルの地下鉄駅は比較的よく記録されていますが、飲食店はどこでも記録が薄いです。都市部から離れるほど、事前の電話確認が効きます。',
    src: (n, d) => `出典：韓国観光公社 TourAPI — バリアフリー観光情報 ${n}件。集計日 ${d}。段差の高さ・扉の幅・トイレの寸法・エレベーターの稼働状況は当サイトに無く、特定の必要に適するという判断もしていません。`
  },
  cal: {
    title: 'いつ韓国に行くか — 月別のお祭り・祝日・混み具合 | Chukjemoa',
    desc: '韓国でこれから開かれるお祭りが月ごとに何件あるか、どの祝日が重なるか、どの地域が混むか。韓国観光公社のデータから。',
    h1: 'いつ行くか — その月に本当に何があるのか',
    lead: (n, months) => `現在、韓国では<b>${n}</b>件のお祭りが開催中または開催予定で、<b>${months}</b>か月にわたっています。「春と秋が良い」という話はどこにでもありますが、ここではもう少し使える形でお見せします。どの月に何件あるか、滞在中にどの祝日が重なるか、どこが混むか。`,
    h2now: '今日やっているもの',
    pNow: (n) => `本日開催中のお祭りは<b>${n}</b>件です。今週のうちに行けるのはこれらです。`,
    until: '〜',
    h2reg: 'お祭りが実際にある場所',
    pReg: (top, n, regions, share) => `開催予定のお祭りは<b>${regions}</b>の広域自治体に散らばっています。最も多いのは<b>${top}</b>で<b>${n}</b>件、それでも全体の<b>${share}%</b>にすぎません。韓国のお祭りは一か所に集中しておらず、大半は初めての旅程では通らない場所で開かれています。`,
    regNote: '開催中・開催予定のお祭りから集計しました。郡の多い道は、単独の市より件数が多く出ます。',
    h2months: '月ごとの件数',
    pMonths: (min) => `件数は国の観光データベースからです。${min}件以上ある月には、その月に開かれるお祭りを全部並べた個別ページがあります。`,
    thMonth: '月', thFes: 'お祭り', thHol: '祝日',
    h2season: '季節ごとに何のための時期か',
    pSeason: '意見ではなく、実際に人がどう動くかから出しています。該当する場所の訪問者数が測定上いちばん増える月です。',
    thWhat: '目的', thBest: 'ピークの月',
    thVal: '渓谷・水遊び', thMap: '紅葉', thFlo: '春の花', thOns: '温泉',
    seasonNote: (ms) => `訪問者の動きは ${ms} 月のみ測定されているため、ピーク月はその測定値から取っています。出典：韓国観光公社「韓国観光データラボ」市郡区別訪問者数。`,
    h2names: 'すべての名前にハングルを併記している理由',
    pNames: '韓国のお祭りは国のデータベースにハングルで登録されていて、公式の日本語名があるものは半分ほどしかありません。公式訳があればそれを使い、無ければローマ字にしています。どちらの場合もハングル原文を併記しているのは、NAVER 地図やカカオマップに貼り付けたときに実際に見つかるのがその文字列だからです。韓国で使える地図アプリはこの二つです。',
    noTrans: '公式訳なし',
    mapLink: 'カカオマップで開く →',
    mTitle: (m) => `韓国のお祭り — ${m}`,
    mLead: (n, m) => `${m}に開催中・開催予定のお祭りは<b>${n}</b>件です。日程・地域・地図リンクを付けて全部並べています。`,
    mHolH: 'この月の祝日',
    mHolP: 'この前後は個人店が休み、都市間の移動手段が埋まります。詳しくは<a href="../../closed/">閉まっている日</a>をご覧ください。',
    mFesH: (m) => `${m}に開かれるもの`,
    mFesP: '開始日順です。灰色はハングル原題で、NAVER 地図やカカオマップに貼ると会場が出ます。',
    mBusyH: '混む地域',
    mBusyP: (m) => `${m}に訪問者数がその地域の年間平均より増える市郡区です。×1.5 は「普段の1.5倍の人がいる」という意味です。`,
    mBusyAlt: (m, meas) => `${m}の訪問者の動きは測定されていないため、測定値のある最も近い月（${meas}月）を表示しています。×1.5 は「普段の1.5倍」という意味です。`,
    mBusyNote: '出典：韓国観光公社「韓国観光データラボ」市郡区別訪問者数。通信・カードデータに基づく推計値で、会場ではなく市郡区全体の数字です。',
    mMeta: (m) => `${m}の韓国のお祭り一覧 — 日程・場所つき | Chukjemoa`,
    mDesc: (n, m) => `${m}に韓国で開かれるお祭り${n}件を、日程・地域・ハングル原題・地図リンク付きで全部。その月の祝日と混み具合も。`
  }
};

const es = {
  nav: { cal: '🗓️ Cuándo ir', acc: '♿ Accesibilidad', trend: '🔥 Rankings', search: '🔎 Festivales', closed: '🚪 Qué cierra y cuándo', trip: '🧳 Según tu visita' },
  daysUnit: (n) => (n === 1 ? ' día' : ' días'),
  cl: {
    title: 'Qué cierra y cuándo en Corea — festivos, día de descanso semanal y pausa de tarde | Chukjemoa',
    desc: 'Los días en que cierran los restaurantes y cafeterías de Corea, contados a partir de los horarios registrados en la base de datos de la Organización de Turismo de Corea y del calendario oficial de festivos.',
    h1: 'Qué está cerrado y cuándo — donde el plan se rompe sin avisar',
    lead: (tot, worstN, worstDay) => `En Corea hay dos formas de encontrarse la persiana bajada: los festivos largos, cuando gran parte de los negocios familiares cierra varios días seguidos, y el <b>día de descanso semanal</b>. Contamos los horarios publicados de <b>${tot}</b> restaurantes y cafeterías registrados en la base de datos de turismo. <b>${worstN}</b> cierran todos los <b>${worstDay}</b>. Esta página trata solo de horarios de apertura: no de visados, dinero ni transporte, sobre los que no tenemos datos.`,
    warnH: (name) => `El próximo cierre largo: ${name}`,
    warnP: (from, to, n) => `<b>${from} – ${to}.</b> Es el mayor desplazamiento interno del año. Los trenes y autobuses interurbanos se agotan semanas antes y los negocios familiares cierran: <b>${n}</b> de los locales de nuestros datos declaran expresamente los festivos como día de cierre, y muchos más cierran sin anunciarlo. Los palacios y los grandes museos suelen abrir; los restaurantes de barrio, no. Si sus fechas caen en esta ventana, apóyese en grandes almacenes, cadenas y tiendas de conveniencia, que siguen abiertos.`,
    h2hol: 'Festivos por delante',
    pHol: (n) => `Hay <b>${n}</b> fechas festivas a partir de hoy. Las fechas consecutivas aparecen agrupadas, porque un puente de tres días no se parece en nada a un festivo suelto.`,
    thDate: 'Fecha', thName: 'Festivo', thDays: 'Duración',
    holNote: 'Cuando un festivo cae en fin de semana se añade un día sustitutivo. Administraciones, bancos y oficinas de correos cierran en todos ellos. La mayoría de atracciones turísticas abre; los negocios pequeños varían.',
    h2week: 'El día de descanso semanal',
    pWeek: (n, day, dn, pct) => `Casi todos los restaurantes coreanos cierran un día fijo a la semana, y casi nunca está indicado en español. De los <b>${n}</b> restaurantes de nuestros datos, <b>${dn}</b> — cerca del <b>${pct}%</b> — cierran los <b>${day}</b>. Es, con diferencia, el día de cierre más frecuente.`,
    h3cafe: 'Las cafeterías siguen el mismo patrón',
    pCafe: (n, day, dn) => `De <b>${n}</b> cafeterías, <b>${dn}</b> cierran los <b>${day}</b>.`,
    weekNote: 'Contado a partir del texto de cierre que cada negocio registró en la base de datos de turismo. Los que no registraron día de cierre no se cuentan aquí, así que la cifra real es mayor, no menor.',
    h2break: 'La pausa de tarde — por qué no se puede comer a las 15:00',
    pBreak: (n, pct, cafeN) => `<b>${n}</b> restaurantes — alrededor del <b>${pct}%</b> de los que tenemos — publican una pausa de media tarde o una hora de última comanda. Normalmente la cocina cierra entre las 15:00 y las 17:00 y vuelve a abrir para la cena. <b>${cafeN}</b> cafeterías también la publican.`,
    pBreak2: 'Así es como se estropea una tarde bien planificada: termina la visita de la mañana a las 14:30, camina veinte minutos hasta el restaurante que había guardado y llega en plena pausa. Coma antes de las 14:00 o después de las 17:00, o compruebe la hora de última comanda antes de salir.',
    h2good: 'La buena noticia',
    pGood: (n, pct, cafeN) => `<b>${n}</b> restaurantes — el <b>${pct}%</b> — figuran como abiertos todos los días del año, junto con <b>${cafeN}</b> cafeterías. Las tiendas de conveniencia abren de verdad 24 horas y están por todas partes. En Corea no se va a quedar sin comer; simplemente algún día no comerá lo que tenía previsto.`,
    pGood2: 'Los grandes almacenes, las cadenas y los patios de comidas junto al metro son los de horario más fiable. Los locales pequeños de dueño único son los menos fiables — y suelen ser los que merecen la pena.',
    h2how: 'Cómo comprobar un sitio concreto',
    pHow: 'Los horarios en Corea son más fiables en Naver Map y Kakao Map que en Google Maps. Ambas funcionan mucho mejor si busca el nombre en coreano, y por eso en este sitio cada lugar aparece con su nombre coreano junto al romanizado. Copie el texto coreano, péguelo en el buscador y lea la línea del horario.',
    src: (rn, cn, d) => `Fuente: TourAPI de la Organización de Turismo de Corea — horarios y días de cierre de ${rn} restaurantes y ${cn} cafeterías · fechas festivas del portal de datos abiertos del Gobierno de Corea. Recuento del ${d}. Los horarios cambian sin aviso; confírmelos antes de viajar.`
  },
  ac: {
    title: 'Viajar por Corea con accesibilidad — lugares registrados por región | Chukjemoa',
    desc: 'Lugares de Corea registrados como accesibles en la base de datos de la Organización de Turismo de Corea, por tipo y región, con una explicación honesta de lo que los datos cubren y lo que no.',
    h1: 'Accesibilidad en Corea — lo que consta realmente',
    lead: (n) => `<b>${n}</b> lugares de Corea están registrados en la base de datos de turismo accesible de la Organización de Turismo de Corea. Es la mayor lista de este tipo que existe y casi nunca se ha publicado en español. Aquí verá qué contiene, dónde está y — igual de importante — <b>dónde los datos son débiles</b>, para que no planifique un viaje sobre cifras que no significan lo que parecen.`,
    h2cat: 'Qué tipo de lugares',
    pCat: (attr, rest) => `Las atracciones son el grupo mayor, con <b>${attr}</b>, seguidas de los restaurantes con <b>${rest}</b>. Estar registrado significa que el titular envió información de accesibilidad a la base de datos nacional: es un punto de partida para investigar, no una garantía de que se cubra una necesidad concreta.`,
    thCat: 'Tipo', thN: 'Lugares',
    h2region: 'Dónde están',
    pRegion: (top, n, seoul, sn) => `<b>${top}</b> es la que más registros tiene, con <b>${n}</b>. ${seoul} tiene <b>${sn}</b>. Conviene leerlo con cuidado: esto refleja <b>con cuánto detalle encuestó cada provincia</b> tanto como su accesibilidad real. Una cifra baja significa que se registró menos, no necesariamente que haya menos lugares accesibles.`,
    h2limit: 'Lea esto antes de fiarse de las etiquetas de detalle',
    pLimit: (wheel, topN, topSido) => `La base también incluye etiquetas como "acceso en silla de ruedas". <b>${wheel}</b> lugares la llevan, pero <b>${topN}</b> de ellos están solo en <b>${topSido}</b>. Es un sesgo de encuesta: una provincia registró etiquetas detalladas y las demás apenas lo hicieron. <b>Fuera de esa provincia, la ausencia de etiqueta no dice casi nada.</b> Lo mostramos en lugar de ocultarlo porque un mapa construido sobre estas etiquetas induciría a error.`,
    h2tags: 'Las etiquetas que existen',
    pTags: 'Recuentos sobre toda la base de datos. Léalos como "tantos registros llevan esta etiqueta", no como "tantos lugares en Corea tienen esto".',
    thTag: 'Característica',
    tag: { '휠체어': 'Acceso en silla de ruedas', '장애인주차': 'Aparcamiento accesible', '장애인화장실': 'Aseo accesible', '엘리베이터': 'Ascensor', '유아·수유': 'Sala de lactancia / cambiador', '시각약자': 'Apoyo para discapacidad visual', '청각약자': 'Apoyo para discapacidad auditiva' },
    h2how: 'Cómo usar esto',
    pHow: 'Use el registro para hacer una preselección y verifique después cada lugar directamente, por teléfono o preguntando en coreano. La entrada sin escalones, las medidas del aseo y el estado del ascensor son justo los detalles que cambian tras una reforma y que casi nunca se actualizan en una base de datos nacional. Las estaciones de metro de Seúl están mucho mejor documentadas que los restaurantes de cualquier sitio; cuanto más se aleje de un área metropolitana, más conviene llamar antes.',
    src: (n, d) => `Fuente: TourAPI de la Organización de Turismo de Corea — información de turismo accesible, ${n} registros. Recuento del ${d}. No disponemos de alturas de escalón, anchos de puerta, medidas de aseos ni estado de ascensores, y no afirmamos que ningún lugar sea adecuado para una necesidad concreta.`
  },
  cal: {
    title: 'Cuándo viajar a Corea — festivales por mes, festivos y afluencia | Chukjemoa',
    desc: 'Cuántos festivales hay cada mes en Corea, qué festivos caen dónde y qué regiones se llenan, a partir de datos de la Organización de Turismo de Corea.',
    h1: 'Cuándo viajar a Corea — qué hay realmente, mes a mes',
    lead: (n, months) => `Ahora mismo hay <b>${n}</b> festivales en marcha o programados en toda Corea, repartidos en <b>${months}</b> meses. Las guías suelen decir que Corea está bien en primavera y otoño. Esta página dice algo más útil: cuántos eventos hay exactamente en cada mes, qué festivos van a cerrar cosas mientras usted está allí y qué zonas se llenan.`,
    h2now: 'Lo que hay ahora mismo',
    pNow: (n) => `Hoy hay <b>${n}</b> festivales abiertos. Son los que podría alcanzar esta misma semana.`,
    until: 'hasta el',
    h2reg: 'Dónde están realmente los festivales',
    pReg: (top, n, regions, share) => `Los festivales previstos se reparten por <b>${regions}</b> provincias y ciudades metropolitanas. <b>${top}</b> es la que más tiene, con <b>${n}</b>, y aun así supone solo el <b>${share}%</b> del total. Los festivales coreanos no se concentran en un punto: la mayoría ocurren en sitios por los que un primer viaje nunca pasa.`,
    regNote: 'Contado sobre los festivales en marcha o programados. Una provincia formada por muchos condados mostrará naturalmente más eventos que una sola ciudad.',
    h2months: 'Mes a mes',
    pMonths: (min) => `Las cifras proceden de la base de datos nacional de turismo. Los meses con al menos ${min} eventos tienen su propia página con la lista completa.`,
    thMonth: 'Mes', thFes: 'Festivales', thHol: 'Festivos',
    h2season: 'Para qué sirve cada temporada',
    pSeason: 'Derivado de cómo se mueven las cifras de visitantes por el país, no de opiniones: son los meses en que los lugares correspondientes se llenan de forma medible.',
    thWhat: 'Para qué', thBest: 'Mes punta',
    thVal: 'Valles y baño', thMap: 'Hojas de otoño', thFlo: 'Flores de primavera', thOns: 'Termas',
    seasonNote: (ms) => `El movimiento de visitantes solo está medido para los meses ${ms}, así que los meses punta salen de esas mediciones. Fuente: Korea Tourism Data Lab, visitantes por distrito.`,
    h2names: 'Por qué cada nombre lleva el coreano al lado',
    pNames: 'Los festivales coreanos figuran en la base de datos nacional con su nombre coreano, y cerca de la mitad no tiene título oficial en otro idioma. Cuando existe traducción oficial la usamos; si no, romanizamos. En ambos casos mostramos el original coreano, porque esa es la cadena que funciona al pegarla en Naver Map o Kakao Map — que son las aplicaciones de mapas que realmente funcionan en Corea.',
    noTrans: 'sin traducción oficial',
    mapLink: 'Abrir en Kakao Map →',
    mTitle: (m) => `Festivales en Corea — ${m}`,
    mLead: (n, m) => `Hay <b>${n}</b> festivales en marcha o programados en ${m}. Están todos listados abajo con fechas, región y enlace al mapa.`,
    mHolH: 'Festivos de este mes',
    mHolP: 'Cuente con que los negocios pequeños cierren y con que el transporte interurbano se llene alrededor de estas fechas. El detalle está en <a href="../../closed/">qué cierra y cuándo</a>.',
    mFesH: (m) => `Todo lo que hay en ${m}`,
    mFesP: 'Ordenado por fecha de inicio. Lo que aparece en gris es el nombre coreano original: péguelo en Naver Map o Kakao Map para localizar el recinto.',
    mBusyH: 'Qué regiones se llenan',
    mBusyP: (m) => `Distritos cuyas cifras de visitantes más suben en ${m} respecto a su propia media anual. Un ×1,5 significa la mitad más de gente de lo habitual.`,
    mBusyAlt: (m, meas) => `El movimiento de visitantes no está medido para ${m}, así que se muestra ${meas}, el mes medido más cercano. Un ×1,5 significa la mitad más de gente de lo habitual en ese distrito.`,
    mBusyNote: 'Fuente: Korea Tourism Data Lab, visitantes por distrito. Son estimaciones basadas en datos de telefonía y tarjetas, y describen el distrito entero, no el recinto concreto.',
    mMeta: (m) => `Festivales coreanos en ${m} — lista completa con fechas y lugares | Chukjemoa`,
    mDesc: (n, m) => `Los ${n} festivales que se celebran en Corea en ${m}, con fechas, regiones, nombres coreanos y enlaces al mapa, más los festivos y la afluencia de ese mes.`
  }
};

const zh = {
  nav: { cal: '🗓️ 什么时候去', acc: '♿ 无障碍', trend: '🔥 人气排行', search: '🔎 庆典搜索', closed: '🚪 哪天关门', trip: '🧳 第几次来韩国' },
  daysUnit: () => '天',
  cl: {
    title: '韩国哪天关门 — 公休日、每周固定休息日、午后休息 | Chukjemoa',
    desc: '韩国餐厅和咖啡馆哪天不营业。数据来自韩国观光公社登记的数千家店铺营业时间，以及官方公休日历。',
    h1: '哪天是关门的 — 行程悄悄崩掉的地方',
    lead: (tot, worstN, worstDay) => `在韩国吃闭门羹通常有两种原因：长假期间大量个体店连着关几天，以及<b>每周固定的休息日</b>。我们统计了韩国观光公社登记的 <b>${tot}</b> 家餐厅和咖啡馆的营业时间，其中 <b>${worstN}</b> 家每逢<b>${worstDay}</b>休息。本页只讲营不营业，不讲签证、换汇和交通——那些我们没有数据。`,
    warnH: (name) => `下一个长假：${name}`,
    warnP: (from, to, n) => `<b>${from} – ${to}。</b>这是一年中人流最大的时段。高铁和长途大巴提前几周就售罄，家庭经营的店铺会关门——我们数据中有 <b>${n}</b> 家明确写着"节日休息"，不声不响关门的还要更多。宫殿和大型美术馆通常照常开放，巷子里的小馆子则不会。如果您的行程正好落在这个区间，请以百货公司、连锁店和便利店为主来安排。`,
    h2hol: '接下来的公休日',
    pHol: (n) => `从今天起共有 <b>${n}</b> 个公休日。连续的日期已合并显示，因为三天连休和单独一天放假完全是两回事。`,
    thDate: '日期', thName: '节日', thDays: '天数',
    holNote: '公休日若与周末重叠会补一天替代公休日。政府机关、银行、邮局这些日子全部休息。旅游景点大多开放，小店则因店而异。',
    h2week: '每周的固定休息日',
    pWeek: (n, day, dn, pct) => `几乎每家韩国餐厅每周都有一天固定休息，而且通常只用韩文写在门口。我们数据中的 <b>${n}</b> 家餐厅里，<b>${dn}</b> 家（约 <b>${pct}%</b>）在<b>${day}</b>休息，远高于其他任何一天。`,
    h3cafe: '咖啡馆也是同样的规律',
    pCafe: (n, day, dn) => `<b>${n}</b> 家咖啡馆中，<b>${dn}</b> 家在<b>${day}</b>休息。`,
    weekNote: '根据各店在韩国观光公社登记的"休息日"字段统计。没有登记休息日的店铺未计入，因此真实数字只会更高。',
    h2break: '午后休息 — 为什么下午三点吃不上饭',
    pBreak: (n, pct, cafeN) => `<b>${n}</b> 家餐厅（约占我们数据的 <b>${pct}%</b>）标注了午后休息时段或最后点餐时间。通常在 15:00 到 17:00 之间关厨房，晚餐时段再开。另有 <b>${cafeN}</b> 家咖啡馆也标注了。`,
    pBreak2: '一个安排得很好的下午常常就这样毁掉：14:30 逛完上午的景点，走二十分钟到心仪的餐厅，正好赶上休息时间。请在 14:00 前或 17:00 后用餐，或者出发前先确认最后点餐时间。',
    h2good: '好消息',
    pGood: (n, pct, cafeN) => `<b>${n}</b> 家餐厅（<b>${pct}%</b>）和 <b>${cafeN}</b> 家咖啡馆登记为全年无休。便利店是真正的 24 小时，而且遍地都是。在韩国不会饿肚子，只是偶尔吃不到原本计划的那一家。`,
    pGood2: '百货公司、大型连锁和地铁站旁的美食广场营业时间最稳定。个体小店最不稳定——而值得去的往往正是后者。',
    h2how: '怎样自己确认某一家店',
    pHow: '在韩国查营业时间，NAVER 地图和 Kakao 地图比 Google 地图准确得多。两者用韩文店名搜索的命中率明显更高，这也是本站每个地名都并列标注韩文的原因。复制韩文粘贴到搜索框，看营业时间那一行即可。',
    src: (rn, cn, d) => `资料来源：韩国观光公社 TourAPI — ${rn} 家餐厅、${cn} 家咖啡馆的营业时间与休息日；公休日期来自韩国政府公共数据门户。统计日期 ${d}。营业时间可能随时变更，出发前请再确认。`
  },
  ac: {
    title: '韩国无障碍旅行 — 已登记设施的地区分布 | Chukjemoa',
    desc: '在韩国观光公社无障碍旅游信息中登记的设施，按类型和地区整理，并如实说明数据覆盖到什么程度。',
    h1: '韩国无障碍旅行 — 记录在案的部分',
    lead: (n) => `韩国观光公社的无障碍旅游信息中登记了 <b>${n}</b> 处设施。这是同类名录中规模最大的，却几乎没有用中文公开过。本页告诉您里面有什么、分布在哪里，以及同样重要的——<b>哪里的数据是薄的</b>，以免您照着看起来不是那个意思的数字安排行程。`,
    h2cat: '都是些什么设施',
    pCat: (attr, rest) => `景点最多，共 <b>${attr}</b> 处，其次是餐厅 <b>${rest}</b> 处。"已登记"意味着经营者向国家数据库提交了无障碍信息，这是查询的起点，并不保证满足某项具体需求。`,
    thCat: '类型', thN: '数量',
    h2region: '分布在哪里',
    pRegion: (top, n, seoul, sn) => `<b>${top}</b>最多，共 <b>${n}</b> 处；${seoul}有 <b>${sn}</b> 处。要留意：这既反映无障碍程度，也同样反映<b>各地调查得有多仔细</b>。数量少代表记录得少，未必代表可用的地方少。`,
    h2limit: '相信细分标签之前请先读这一段',
    pLimit: (wheel, topN, topSido) => `数据里还有"轮椅"之类的细分标签。带轮椅标签的有 <b>${wheel}</b> 处，但其中 <b>${topN}</b> 处集中在<b>${topSido}</b>一地。这是调查偏差：只有一个道记录了细分标签，其他地方基本没记。<b>因此在该道以外，"没有标签"几乎说明不了任何问题。</b>我们把它写出来而不是藏起来，是因为用这些标签做地图会实实在在地误导人。`,
    h2tags: '现有的细分标签',
    pTags: '这是整个数据库的计数。请理解为"有这么多条记录带此标签"，而不是"韩国有这么多地方具备此条件"。',
    thTag: '项目',
    tag: { '휠체어': '轮椅通行', '장애인주차': '无障碍停车位', '장애인화장실': '无障碍卫生间', '엘리베이터': '电梯', '유아·수유': '育婴·哺乳室', '시각약자': '视障支持', '청각약자': '听障支持' },
    h2how: '怎么用这份名录',
    pHow: '把它当作候选清单，最后一定要逐一直接确认——打电话，或用韩文询问店家。无台阶入口、卫生间尺寸、电梯是否运行，恰恰是装修后就会变、而国家数据库几乎不会更新的细节。首尔地铁站的记录远比任何地方的餐厅完整；离大城市越远，越应该提前打电话。',
    src: (n, d) => `资料来源：韩国观光公社 TourAPI — 无障碍旅游信息 ${n} 条。统计日期 ${d}。我们没有台阶高度、门宽、卫生间尺寸和电梯运行状态的数据，也不对任何场所是否适合某项具体需求作出判断。`
  },
  cal: {
    title: '什么时候去韩国 — 分月庆典、公休日与拥挤度 | Chukjemoa',
    desc: '韩国接下来每个月有多少庆典、哪些公休日落在哪里、哪些地区会挤，数据来自韩国观光公社。',
    h1: '什么时候去 — 那个月到底有什么',
    lead: (n, months) => `目前韩国共有 <b>${n}</b> 场庆典正在举行或已排定，分布在 <b>${months}</b> 个月里。"春秋两季最好"这种话到处都有，这一页给的是更能用的东西：每个月究竟有多少场、您在的时候会撞上哪些公休日、哪些地方会挤。`,
    h2now: '今天正在办的',
    pNow: (n) => `今天正在举行的庆典有 <b>${n}</b> 场，这些是本周就能赶上的。`,
    until: '至',
    h2reg: '庆典其实分布在哪里',
    pReg: (top, n, regions, share) => `已排定的庆典分布在 <b>${regions}</b> 个道与广域市。最多的是<b>${top}</b>，共 <b>${n}</b> 场，即便如此也只占全体的 <b>${share}%</b>。韩国的庆典并不集中在一处，大多数都办在初次行程根本不会经过的地方。`,
    regNote: '依正在举行或已排定的庆典统计。郡较多的道，场次自然会比单一城市多。',
    h2months: '逐月一览',
    pMonths: (min) => `场次来自国家旅游数据库。满 ${min} 场以上的月份有独立页面，把当月全部庆典列出来。`,
    thMonth: '月份', thFes: '庆典', thHol: '公休日',
    h2season: '每个季节到底适合做什么',
    pSeason: '这不是主观意见，而是从全国访客数的实际变化推出来的——是相应场所在统计上确实变挤的月份。',
    thWhat: '想做什么', thBest: '高峰月',
    thVal: '溪谷戏水', thMap: '红叶', thFlo: '春花', thOns: '温泉',
    seasonNote: (ms) => `访客流动只测量了 ${ms} 月，因此高峰月份取自这些测量值。资料来源：韩国观光公社「韩国观光数据实验室」市郡区访客数。`,
    h2names: '为什么每个名字旁边都有韩文',
    pNames: '韩国的庆典在国家数据库里以韩文登记，约有一半没有官方外文名。有官方译名的我们直接用，没有的就转写成罗马字。两种情况下都并列韩文原名，因为粘贴到 NAVER 地图或 Kakao 地图时真正能搜到的正是那串字——而这两个才是在韩国真正好用的地图应用。',
    noTrans: '无官方译名',
    mapLink: '在 Kakao 地图打开 →',
    mTitle: (m) => `韩国的庆典 — ${m}`,
    mLead: (n, m) => `${m}正在举行或已排定的庆典共 <b>${n}</b> 场，下面全部列出，附日期、地区和地图链接。`,
    mHolH: '本月公休日',
    mHolP: '这几天前后小店会关门，城际交通会紧张。详见<a href="../../closed/">哪天关门</a>。',
    mFesH: (m) => `${m}有什么`,
    mFesP: '按开始日期排序。灰色是韩文原名，粘贴到 NAVER 地图或 Kakao 地图即可找到会场。',
    mBusyH: '哪些地区会挤',
    mBusyP: (m) => `${m}访客数相对该地区自身年均值上升最多的市郡区。×1.5 表示人比平时多出一半。`,
    mBusyAlt: (m, meas) => `${m}的访客流动没有测量数据，这里显示最接近的已测月份（${meas}月）。×1.5 表示该地区人比平时多出一半。`,
    mBusyNote: '资料来源：韩国观光公社「韩国观光数据实验室」市郡区访客数。这是基于通信和信用卡数据的推估值，描述的是整个市郡区，而不是具体场馆。',
    mMeta: (m) => `${m}韩国庆典完整列表 — 含日期与地点 | Chukjemoa`,
    mDesc: (n, m) => `${m}在韩国举行的 ${n} 场庆典，含日期、地区、韩文原名和地图链接，以及当月公休日与拥挤度。`
  }
};

const tw = {
  nav: { cal: '🗓️ 什麼時候去', acc: '♿ 無障礙', trend: '🔥 人氣排行', search: '🔎 慶典搜尋', closed: '🚪 哪天休息', trip: '🧳 第幾次來韓國' },
  daysUnit: () => '天',
  cl: {
    title: '韓國哪天休息 — 國定假日、每週公休、午後休息 | Chukjemoa',
    desc: '韓國餐廳與咖啡廳哪天不營業。資料取自韓國觀光公社登錄的數千家店營業時間，以及官方國定假日行事曆。',
    h1: '哪天是關著的 — 行程悄悄垮掉的地方',
    lead: (tot, worstN, worstDay) => `在韓國撲空通常有兩個原因：連假期間大量個人店連著休好幾天，以及<b>每週固定的公休日</b>。我們統計了韓國觀光公社登錄的 <b>${tot}</b> 家餐廳與咖啡廳的營業時間，其中 <b>${worstN}</b> 家每逢<b>${worstDay}</b>公休。本頁只談有沒有開，不談簽證、換匯與交通——那些我們沒有資料。`,
    warnH: (name) => `下一個長假：${name}`,
    warnP: (from, to, n) => `<b>${from} – ${to}。</b>這是一年中人流最大的時段。高鐵與客運提前數週售罄，家族經營的店會休息——我們資料中有 <b>${n}</b> 家明確寫著「節日公休」，不聲不響關門的還更多。宮殿與大型美術館通常照開，巷子裡的小館子則不會。行程若落在這個區間，請以百貨公司、連鎖店與便利商店為主軸安排。`,
    h2hol: '接下來的國定假日',
    pHol: (n) => `從今天起共有 <b>${n}</b> 個國定假日。連續的日期已合併顯示，因為三天連假和單獨一天放假完全是兩回事。`,
    thDate: '日期', thName: '假日', thDays: '天數',
    holNote: '假日若與週末重疊會補一天替代假日。政府機關、銀行、郵局這幾天全部休息。觀光景點多半開放，小店則因店而異。',
    h2week: '每週的固定公休日',
    pWeek: (n, day, dn, pct) => `幾乎每家韓國餐廳每週都有一天固定公休，而且通常只用韓文寫在門口。我們資料中的 <b>${n}</b> 家餐廳裡，<b>${dn}</b> 家（約 <b>${pct}%</b>）在<b>${day}</b>公休，遠高於其他任何一天。`,
    h3cafe: '咖啡廳也是同樣的規律',
    pCafe: (n, day, dn) => `<b>${n}</b> 家咖啡廳中，<b>${dn}</b> 家在<b>${day}</b>公休。`,
    weekNote: '依各店在韓國觀光公社登錄的「公休日」欄位統計。沒有登錄公休日的店未計入，因此實際數字只會更高。',
    h2break: '午後休息 — 為什麼下午三點吃不到飯',
    pBreak: (n, pct, cafeN) => `<b>${n}</b> 家餐廳（約占我們資料的 <b>${pct}%</b>）標註了午後休息時段或最後點餐時間。通常在 15:00 到 17:00 之間收廚房，晚餐時段再開。另有 <b>${cafeN}</b> 家咖啡廳也有標註。`,
    pBreak2: '安排得好好的下午常常就這樣毀了：14:30 逛完上午的景點，走二十分鐘到看好的餐廳，剛好撞上休息時間。請在 14:00 前或 17:00 後用餐，或出發前先確認最後點餐時間。',
    h2good: '好消息',
    pGood: (n, pct, cafeN) => `<b>${n}</b> 家餐廳（<b>${pct}%</b>）與 <b>${cafeN}</b> 家咖啡廳登錄為全年無休。便利商店是真正的 24 小時，而且到處都是。在韓國不會餓到，只是偶爾吃不到原本計畫的那一家。`,
    pGood2: '百貨公司、大型連鎖與捷運站旁的美食街營業時間最穩定。個人小店最不穩定——而值得去的往往正是後者。',
    h2how: '怎麼自己確認某一家店',
    pHow: '在韓國查營業時間，NAVER 地圖與 Kakao 地圖比 Google 地圖準得多。兩者用韓文店名搜尋的命中率明顯較高，這也是本站每個地名都並列韓文的原因。複製韓文貼到搜尋框，看營業時間那一行即可。',
    src: (rn, cn, d) => `資料來源：韓國觀光公社 TourAPI — ${rn} 家餐廳、${cn} 家咖啡廳的營業時間與公休日；假日日期取自韓國政府公共資料入口網。統計日期 ${d}。營業時間可能隨時變更，出發前請再確認。`
  },
  ac: {
    title: '韓國無障礙旅行 — 已登錄設施的地區分布 | Chukjemoa',
    desc: '登錄於韓國觀光公社無障礙觀光資訊的設施，依類型與地區整理，並如實說明資料涵蓋到什麼程度。',
    h1: '韓國無障礙旅行 — 有紀錄的部分',
    lead: (n) => `韓國觀光公社的無障礙觀光資訊中登錄了 <b>${n}</b> 處設施。這是同類名錄中規模最大的，卻幾乎沒有以中文公開過。本頁告訴您裡面有什麼、分布在哪裡，以及同樣重要的——<b>哪裡的資料是薄的</b>，以免您照著看起來不是那個意思的數字安排行程。`,
    h2cat: '都是些什麼設施',
    pCat: (attr, rest) => `景點最多，共 <b>${attr}</b> 處，其次是餐廳 <b>${rest}</b> 處。「已登錄」是指業者向國家資料庫提交了無障礙資訊，這是查詢的起點，並不保證滿足某項具體需求。`,
    thCat: '類型', thN: '數量',
    h2region: '分布在哪裡',
    pRegion: (top, n, seoul, sn) => `<b>${top}</b>最多，共 <b>${n}</b> 處；${seoul}有 <b>${sn}</b> 處。要留意：這既反映無障礙程度，也同樣反映<b>各地調查得有多仔細</b>。數量少代表紀錄得少，未必代表可用的地方少。`,
    h2limit: '相信細項標籤之前請先讀這一段',
    pLimit: (wheel, topN, topSido) => `資料裡還有「輪椅」之類的細項標籤。帶輪椅標籤的有 <b>${wheel}</b> 處，但其中 <b>${topN}</b> 處集中在<b>${topSido}</b>一地。這是調查偏差：只有一個道記錄了細項標籤，其他地方基本沒記。<b>因此在該道以外，「沒有標籤」幾乎說明不了任何事。</b>我們把它寫出來而不是藏起來，是因為用這些標籤做地圖會實實在在地誤導人。`,
    h2tags: '現有的細項標籤',
    pTags: '這是整個資料庫的計數。請理解為「有這麼多筆紀錄帶此標籤」，而不是「韓國有這麼多地方具備此條件」。',
    thTag: '項目',
    tag: { '휠체어': '輪椅通行', '장애인주차': '無障礙停車位', '장애인화장실': '無障礙廁所', '엘리베이터': '電梯', '유아·수유': '育嬰・哺乳室', '시각약자': '視障支援', '청각약자': '聽障支援' },
    h2how: '怎麼用這份名錄',
    pHow: '把它當候選清單，最後一定要逐一直接確認——打電話，或用韓文詢問店家。無台階入口、廁所尺寸、電梯是否運行，正是裝修後就會變、而國家資料庫幾乎不會更新的細節。首爾捷運站的紀錄遠比任何地方的餐廳完整；離大城市越遠，越該提前打電話。',
    src: (n, d) => `資料來源：韓國觀光公社 TourAPI — 無障礙觀光資訊 ${n} 筆。統計日期 ${d}。我們沒有台階高度、門寬、廁所尺寸與電梯運行狀態的資料，也不對任何場所是否適合某項具體需求作出判斷。`
  },
  cal: {
    title: '什麼時候去韓國 — 分月慶典、假日與擁擠度 | Chukjemoa',
    desc: '韓國接下來每個月有多少慶典、哪些假日落在哪裡、哪些地區會擠，資料取自韓國觀光公社。',
    h1: '什麼時候去 — 那個月到底有什麼',
    lead: (n, months) => `目前韓國共有 <b>${n}</b> 場慶典正在舉行或已排定，分布在 <b>${months}</b> 個月裡。「春秋兩季最好」這種話到處都有，這一頁給的是更能用的東西：每個月究竟有幾場、您在的時候會撞上哪些假日、哪些地方會擠。`,
    h2now: '今天正在辦的',
    pNow: (n) => `今天正在舉行的慶典有 <b>${n}</b> 場，這些是本週就趕得上的。`,
    until: '至',
    h2reg: '慶典其實分布在哪裡',
    pReg: (top, n, regions, share) => `已排定的慶典分布在 <b>${regions}</b> 個道與廣域市。最多的是<b>${top}</b>，共 <b>${n}</b> 場，即便如此也只占全體的 <b>${share}%</b>。韓國的慶典並不集中在一處，大多數都辦在初次行程根本不會經過的地方。`,
    regNote: '依正在舉行或已排定的慶典統計。郡較多的道，場次自然會比單一城市多。',
    h2months: '逐月一覽',
    pMonths: (min) => `場次取自國家觀光資料庫。滿 ${min} 場以上的月份有獨立頁面，把當月全部慶典列出來。`,
    thMonth: '月份', thFes: '慶典', thHol: '假日',
    h2season: '每個季節到底適合做什麼',
    pSeason: '這不是主觀意見，而是從全國訪客數的實際變化推出來的——是相應場所在統計上確實變擠的月份。',
    thWhat: '想做什麼', thBest: '高峰月',
    thVal: '溪谷戲水', thMap: '楓葉', thFlo: '春花', thOns: '溫泉',
    seasonNote: (ms) => `訪客流動只測量了 ${ms} 月，因此高峰月份取自這些測量值。資料來源：韓國觀光公社「韓國觀光數據實驗室」市郡區訪客數。`,
    h2names: '為什麼每個名字旁邊都有韓文',
    pNames: '韓國的慶典在國家資料庫以韓文登錄，約有一半沒有官方外文名。有官方譯名的我們直接用，沒有的就轉寫成羅馬字。兩種情況都並列韓文原名，因為貼到 NAVER 地圖或 Kakao 地圖時真正搜得到的正是那串字——而這兩個才是在韓國真正好用的地圖應用。',
    noTrans: '無官方譯名',
    mapLink: '在 Kakao 地圖開啟 →',
    mTitle: (m) => `韓國的慶典 — ${m}`,
    mLead: (n, m) => `${m}正在舉行或已排定的慶典共 <b>${n}</b> 場，下面全部列出，附日期、地區與地圖連結。`,
    mHolH: '本月假日',
    mHolP: '這幾天前後小店會休息，城際交通會很滿。詳見<a href="../../closed/">哪天休息</a>。',
    mFesH: (m) => `${m}有什麼`,
    mFesP: '依開始日期排序。灰色是韓文原名，貼到 NAVER 地圖或 Kakao 地圖即可找到會場。',
    mBusyH: '哪些地區會擠',
    mBusyP: (m) => `${m}訪客數相對該地區自身年均值上升最多的市郡區。×1.5 表示人比平常多出一半。`,
    mBusyAlt: (m, meas) => `${m}的訪客流動沒有測量資料，這裡顯示最接近的已測月份（${meas}月）。×1.5 表示該地區人比平常多出一半。`,
    mBusyNote: '資料來源：韓國觀光公社「韓國觀光數據實驗室」市郡區訪客數。這是基於通訊與信用卡資料的推估值，描述的是整個市郡區，而不是具體場館。',
    mMeta: (m) => `${m}韓國慶典完整列表 — 含日期與地點 | Chukjemoa`,
    mDesc: (n, m) => `${m}在韓國舉行的 ${n} 場慶典，含日期、地區、韓文原名與地圖連結，以及當月假日與擁擠度。`
  }
};

module.exports = { en, ja, es, zh, tw };
